#!/bin/sh

REGISTRY="${DOCKER_LOCAL_REGISTRY}"
IMAGE="node:10"
FULL="${REGISTRY}${IMAGE}"

if [ -z "${PORT}" ] ; then
	PORTSTR=
else
	PORTSTR="-p ${PORT}:8080"
fi

WORKDIR="/app"
docker run \
	--user "node" \
	-it \
	${PORTSTR} \
	--rm \
	-w "${WORKDIR}" \
	-v "$(pwd):${WORKDIR}" \
	"${FULL}" "$@"
