#!/bin/sh

# This is duplicating some code from the node script because we can't use the
# -it flags because the input device is not a tty when called by git commit.

REGISTRY="${DOCKER_LOCAL_REGISTRY}"
IMAGE="node:10"
FULL="${REGISTRY}${IMAGE}"

WORKDIR="/app"
docker run \
	--user "node" \
	--rm \
	-w "${WORKDIR}" \
	-v "$(pwd):${WORKDIR}" \
	"${FULL}" npm run precommit -s
